version: "3.9"

services:
  backend:
    build: ./backend
    container_name: calendly-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  db:
    image: postgres:14
    container_name: calendly-db
    restart: always
    environment:
      POSTGRES_DB: calendly
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: calendly-redis
    restart: always
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: calendly-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
